# Generated by Django 4.2.6 on 2023-11-02 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postpage_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postpage',
            name='post_image',
        ),
    ]
